spring:
  application:
    name: spring-ai-alibaba-learning
  config:
    import: optional:file:.env[.properties]

  ai:
    chat:
    dashscope:
#        生产环境强烈推荐使用环境变量（或等效的外部化配置），而不是把密钥硬编码在
      api-key: ${AI_DASHSCOPE_API_KEY}
#      chat:
#        options:
#          model: qwen3.7-flash
#          multi-model: true


server:
  port: 18080

# springdoc / Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

